"""Unit + integration tests for :class:`FileInfoExtractor`.

Fixtures are deterministic (regenerated by ``scripts/build_fixtures.py``)
and their SHA-256 values are committed to source so we can assert on
hash stability without the test computing-its-own-expected-value tautology.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from PIL import Image

from pixel_probe.core.extractors import file_info as file_info_module
from pixel_probe.core.extractors.base import ExtractorResult
from pixel_probe.core.extractors.file_info import FileInfo, FileInfoExtractor
from pixel_probe.exceptions import DecompressionBombError, FileTooLargeError, MissingFileError

from .conftest import fixture_path

# Deterministic byte/SHA values for the committed fixtures. Regenerated by
# scripts/build_fixtures.py — keep in sync if Pillow's encoder output changes.
TINY_JPG_SIZE = 285
TINY_JPG_SHA = "d02ca6bbf6a4d459053b6c2f670ceb8e5d0049cedb1ca9195ff13fa953861f69"
TINY_PNG_SHA = "f2bb5bbaca678ecad746b1fa5ecfa2c8a81dd18817be19f0187c036d25326317"


def _data(result: ExtractorResult[FileInfo]) -> FileInfo:
    """Type-narrowing helper — Mypy can't see that test fixtures always populate `data`."""
    assert result.data is not None
    return result.data


def test_extracts_basic_jpeg() -> None:
    result = FileInfoExtractor().extract(fixture_path("tiny.jpg"))

    assert result.extractor_name == "file_info"
    assert result.warnings == ()
    assert result.errors == ()
    assert result.has_data

    info = _data(result)
    assert info.format == "JPEG"
    assert info.mode == "RGB"
    assert (info.width, info.height) == (1, 1)
    assert info.size_bytes == TINY_JPG_SIZE
    assert info.sha256 == TINY_JPG_SHA


def test_extracts_basic_png() -> None:
    result = FileInfoExtractor().extract(fixture_path("tiny.png"))

    info = _data(result)
    assert info.format == "PNG"
    assert info.mode == "RGBA"
    assert (info.width, info.height) == (1, 1)
    assert info.sha256 == TINY_PNG_SHA


def test_sha256_matches_committed_fixture() -> None:
    """Hash assertion is not redundant with the dimension assertion above —
    it independently catches accidental fixture corruption / re-encoding."""
    info = _data(FileInfoExtractor().extract(fixture_path("tiny.jpg")))
    assert info.sha256 == TINY_JPG_SHA


def test_missing_file_raises_missing_file_error(tmp_path: Path) -> None:
    """Catastrophic failure raises a typed :class:`MissingFileError` (a
    :class:`PixelProbeError` subclass) — the orchestrator (not us) decides
    whether to keep going. Keeping it inside the project's exception hierarchy
    means callers can ``except PixelProbeError`` and catch every extractor
    failure with one clause."""
    with pytest.raises(MissingFileError):
        FileInfoExtractor().extract(tmp_path / "does-not-exist.jpg")


def test_non_image_warns_but_does_not_crash() -> None:
    """A plaintext file isn't an image, but we still want the file metadata
    (size, hash, mtime) — only the image-format fields go ``None`` and a
    warning records the partial-extraction outcome."""
    result = FileInfoExtractor().extract(fixture_path("not_an_image.txt"))

    assert result.errors == ()
    assert result.warnings == ("File is not a recognized image format",)

    info = _data(result)
    assert info.format is None
    assert info.mode is None
    assert info.width is None
    assert info.height is None
    assert info.size_bytes > 0  # the file itself is real, just not an image
    assert info.sha256  # still computed


def test_oversized_file_raises_file_too_large(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Reject huge files before any read begins — DoS / decompression-bomb gate."""
    big = tmp_path / "fake-huge.bin"
    big.write_bytes(b"\x00" * 1000)

    monkeypatch.setattr(file_info_module, "MAX_FILE_SIZE_BYTES", 100)

    with pytest.raises(FileTooLargeError) as exc_info:
        FileInfoExtractor().extract(big)

    assert "1,000 bytes" in str(exc_info.value)
    assert "max is 100" in str(exc_info.value)


def test_decompression_bomb_chains_pillow_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A pixel count over our ``MAX_IMAGE_PIXELS`` raises our typed error,
    with Pillow's original chained as ``__cause__`` for debuggability —
    this is the security signal mentioned in the testing strategy.

    Pillow only raises ``DecompressionBombError`` above ``2x MAX_IMAGE_PIXELS``.
    Below that, it emits ``DecompressionBombWarning`` — we escalate the warning
    to an error in ``file_info.py`` so bombs are caught at the configured
    threshold, not at 2x it. Either origin is acceptable as ``__cause__``.
    """
    img_path = tmp_path / "small.png"
    Image.new("RGB", (10, 10)).save(img_path)

    # Tighten the bomb threshold so the 100-pixel image trips it.
    monkeypatch.setattr(file_info_module, "MAX_IMAGE_PIXELS", 50)

    with pytest.raises(DecompressionBombError) as exc_info:
        FileInfoExtractor().extract(img_path)

    assert isinstance(
        exc_info.value.__cause__,
        Image.DecompressionBombError | Image.DecompressionBombWarning,
    )


def test_pillow_max_pixels_is_restored_on_success(tmp_path: Path) -> None:
    """``Image.MAX_IMAGE_PIXELS`` is process-global — we MUST restore it
    so other code in the same process isn't affected by our tighter limit."""
    img_path = tmp_path / "small.png"
    Image.new("RGB", (10, 10)).save(img_path)

    original = Image.MAX_IMAGE_PIXELS
    FileInfoExtractor().extract(img_path)
    assert original == Image.MAX_IMAGE_PIXELS


def test_pillow_max_pixels_is_restored_on_bomb(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Same restore guarantee, even when the extractor raises on the way out."""
    img_path = tmp_path / "small.png"
    Image.new("RGB", (10, 10)).save(img_path)

    monkeypatch.setattr(file_info_module, "MAX_IMAGE_PIXELS", 50)
    original = Image.MAX_IMAGE_PIXELS

    with pytest.raises(DecompressionBombError):
        FileInfoExtractor().extract(img_path)

    assert original == Image.MAX_IMAGE_PIXELS


def test_idempotent() -> None:
    """Same input → same output, every call. The whole testing strategy
    (deterministic SHAs, reproducible fixtures) hinges on this."""
    extractor = FileInfoExtractor()
    a = extractor.extract(fixture_path("tiny.jpg"))
    b = extractor.extract(fixture_path("tiny.jpg"))
    assert _data(a) == _data(b)
